### ISSUE TITLE
Problem about RNN encoder-decoder

### ISSUE THREAD

**Issue by ShuoW** [hugman/deep_learning#1]
Hi,

I have mentioned that you ask some people to implement the RNN encoder-decoder. Now I also try to implement it with Keras. Can you provide your implemented codes as an example for me?

Thanks.

Shuo

**Comment by hugman** [comment]
Sorry to replay too late. 
Recently, I use tensorflow as my first deep learning tool, so I didn't implement anythings on keras. 

RNN encoder and decoder implementation using tensorflow is very easy, and there are many good examples. 

please check  : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/rnn
